### ISSUE TITLE
ApplicationName is not a Valid Input for Metadata Module

### ISSUE THREAD

**Issue by riesbl01** [Azure-Terraform/terraform-azurerm-metadata#6]
There are several naming schemes in the python-azure-naming repo that use the ApplicationName naming scheme. Like the other naming schemes, that name should be a valid input for the metadata module, but there is no input defined for it currently. Ideally we would add a input variable application_name to the metadata module.

**Comment by faraday23** [comment]
Please add 'application_name' to module because I was attempting to follow the naming convention for network interfaces when I noticed 'application_name' is not supported with this metadata module.

![network_interface](https://user-images.githubusercontent.com/41235618/106902851-48276b00-66c7-11eb-9af1-99e62ed53e6a.PNG)
